#!/usr/bin/env bash

options=(
    ""
    ""
    ""
    ""
    ""
)

rofi_cmd() {
	rofi -dmenu \
		-p "Goodbye ${USER}" \
		-mesg "Uptime: $(uptime -p | sed -e 's/up //g')" \
		-theme "$HOME"/.config/bspwm/src/rofi-themes/PowerMenu.rasi
}

chosen=$(printf "%s\n" "${options[@]}" | rofi_cmd)

case $chosen in
    "")
        sudo poweroff
        ;;
    "")
        sudo reboot
        ;;
    "")
        physlock -d
        ;;
    "")
        mpc -q pause
        amixer set Master mute
        sudo suspend
        ;;
    "")
        bspc quit
        ;;
esac
