#!/usr/bin/env bash
#  ╔═╗╦═╗╔═╗╦ ╦  ╦ ╦╔═╗╔╦╗╔═╗╔╦╗╔═╗╔═╗
#  ╠═╣╠╦╝║  ╠═╣  ║ ║╠═╝ ║║╠═╣ ║ ║╣ ╚═╗
#  ╩ ╩╩╚═╚═╝╩ ╩  ╚═╝╩  ═╩╝╩ ╩ ╩ ╚═╝╚═╝
# Script to check for new updates in arch and AUR. Copyright 2023 gh0stzk
# Author: z0mbi3
# Modified by: Glozzom
# url: https://github.com/gh0stzk

get_total_updates() {
    local total_updates
    
    total_updates=$(sudo xbps-install -Sun 2> /dev/null | wc -l || echo 0)
    echo "${total_updates:-0}"
}

get_list_updates() {
    echo -e "\033[1m\033[34mRegular updates:\033[0m"
     sudo xbps-install -Sun | awk '{print $1}'
}

print_updates() {
	local print_updates
    print_updates=$(get_total_updates)

    if [[ "$print_updates" -gt 0 ]]; then
        echo -e "\033[1m\033[33mThere are $print_updates updates available:\033[0m\n"
        get_list_updates
    else
        echo -e "\033[1m\033[32mYour system is already updated!\033[0m"
    fi
}

update_system() {
    sudo xbps-install -Syu
}

case "$1" in
    --get-updates) get_total_updates ;;
    --print-updates) print_updates ;;
    --update-system) update_system ;;
    --help|*)echo -e "Updates [options]

Options:
	--get-updates		Get the number of updates available.
	--print-updates		Print the number of available package to update.
	--update-system		Update your system including the AUR packages.\n"
esac
